### PR TITLE
Port string extensions and test case name parser utilities

### PR DESCRIPTION
**Pull request by Siphonophora**
I think this should be in pretty good shape as a starting point.

### CODE REVIEW

**Comment by Siphonophora** [comment]
Actually, looks like I should probably revert the last commit, since not all the loggers use xml. At least, the json one in the project doesn't.

**Comment by Siphonophora** [comment]
@codito What do you think we should do with this? As I said above, I should probably revert d950891 because its xml specific and not all the loggers use xml. 

Also, I can resolve https://github.com/spekt/nunit.testlogger/issues/64 and https://github.com/spekt/nunit.testlogger/issues/66 here instead of in that project.

**Comment by codito** [comment]
We will merge this one soon. The part I am still thinking about is the right abstractions for the Core logger. It's currently inheritance based, we should brainstorm a bit if that will allow us enough composability (worried that the base logger class may become a god class).

**Comment by codito** [comment]
@Siphonophora the initial design is up for review: https://github.com/spekt/testlogger/pull/9. Please take a look and share any feedback.

**Comment by codito** [comment]
Closing this PR since we have ported this functionality in another commit.

**Pull request closed without merging**
